### ISSUE TITLE
Parsing failure case in v4 & workaround patch

### ISSUE THREAD

**Issue by xloem** [fox-it/dissect.cstruct#62]
```
from dissect.cstruct import cstruct
cdef = '''
struct {
  int32 len;
  char str[len];
} subt;
struct {
  subt data[1];
} obj;
'''
cstruct().load(cdef)
```

```
Traceback (most recent call last):
  File "case.py", line 12, in <module>
    cstruct().load(cdef)
  File "dissect/cstruct/cstruct.py", line 238, in load
    TokenParser(self, **kwargs).parse(definition)
  File "dissect/cstruct/parser.py", line 367, in parse
    self._struct(tokens, register=True)
  File "dissect/cstruct/parser.py", line 204, in _struct
    field = self._parse_field(tokens)
  File "dissect/cstruct/parser.py", line 290, in _parse_field
    type_ = self.cstruct._make_array(type_, count)
  File "dissect/cstruct/cstruct.py", line 316, in _make_array
    size = None if null_terminated or dynamic else num_entries * type_.size
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

```
diff --git a/dissect/cstruct/cstruct.py b/dissect/cstruct/cstruct.py
index 617e9b7..be6cb03 100644
--- a/dissect/cstruct/cstruct.py
+++ b/dissect/cstruct/cstruct.py
@@ -304,7 +304,7 @@ class cstruct:
             {
                 "cs": self,
                 "size": size,
-                "dynamic": size is None,
+                "dynamic": attrs.get("dynamic", size is None),
                 "alignment": alignment or size,
             }
         )
@@ -313,7 +313,7 @@ class cstruct:
     def _make_array(self, type_: MetaType, num_entries: Optional[UnionHint[int, Expression]]) -> type[Array]:
         null_terminated = num_entries is None
         dynamic = isinstance(num_entries, Expression)
-        size = None if null_terminated or dynamic else num_entries * type_.size
+        size = None if null_terminated or dynamic or type_.size is None else num_entries * type_.size
         name = f"{type_.__name__}[]" if null_terminated else f"{type_.__name__}[{num_entries}]"
 
         bases = (Array,)
```

**Comment by Schamper** [comment]
Nice catch! This should be fixed with https://github.com/fox-it/dissect.cstruct/pull/35/commits/b5badc987456f4f60e5a8982a7cb5d2825626934 in the v4 branch. I don't think the `"dynamic": attrs.get("dynamic", size is None),` addition is strictly necessary, but perhaps I'm missing something?

**Comment by Schamper** [comment]
Thanks, good catch! https://github.com/fox-it/dissect.cstruct/pull/35/commits/b5badc987456f4f60e5a8982a7cb5d2825626934 should fix this in the v4 branch. I don't think your change in `_make_type` is necessary though, unless I missed something?

**Comment by xloem** [comment]
It was needed in my workaround to prevent another exception. It sounds like you used understanding of the underlying meaning to fix it correctly. Great!
